<!-- 公用底部 -->
<div class="footer bt">
    <p class="copyright">学生信息管理系统是针对学校学生处的大量业务处理工作而开发的管理软件，主要用于学校学生信息管理，</p>
    <p > 总体任务是实现学生信息关系的系统化、科学化、规范化和自动化，其主要任务是用计算机对学生各种信息进行日常管理，</p>
    <p> 如查询、修改、增加、删除，另外还考虑到学生选课，针对这些要求设计了学生信息管理系统。<br></p>
</div>
<script src="/admin/js/dialog.js"></script>
<script src="/admin/js/calendar.js"></script>
<script src="/admin/js/common.js"></script>
<script src="/admin/js/tingyun-rum.js"></script>
</body>
</html>
