<!DOCTYPE html>
<html lang="zh-hans"><head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="UTF-8">
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <link rel="stylesheet" type="text/css" href="">
    <title></title>
    <link rel="icon" href="http://help-t.yaochufa.com/favicon.ico" type="image/x-icon">
    <link rel="stylesheet" href="/admin/css/common.css">
    <link rel="stylesheet" href="/admin/css/calendar.css">
    <link rel="stylesheet" href="/admin/css/dialog.css">
    <script src="/admin/js/jquery.js"></script>
    <style>
        button.btn-middle {vertical-align: middle;}
        .calendar-wrapper{display: inline-block;*display:inline;zoom:1;}
        .calendar-wrapper div{vertical-align: middle;}

    </style>
</head>
<body>
