<?php $this->partial('common/top');?>
    <div class="header bb">
        <!-- 导航栏 -->
        <div class="menu" id="J-menu">
            <!-- 顶栏 -->
            <div class="wrapper clearfix">
                <a href="/admin/student/index" class="logo fl">
                    <img src="/admin/images/logo-new.png" alt="logo">
                    <span style="color: #29a2da;font-weight: 900;">学生管理系统</span>
                </a>
                <ol class="clearfix fl" id="J-menu-item">
                    <li class="active" data-index="3">
                        <a href="/admin/student/index" class="first" >学生列表<i class="icon-css icon-css-tb"></i></a>
                        <!--<i class="icon icon-submenu submenu3"></i>-->
                        <div>
                            <a href="">信息院</a>
                            <a href="">化院</a>
                            <a href="">物电学院</a>
                            <a href="">外国语学院</a>
                            <a href="">文学院</a>
                            <a href="">体育学院</a>
                            <a href="">经济学院</a>
                        </div>
                    </li>
                    <li data-index="2">
                        <a href="/admin/course/index" class="first">课程列表<i class="icon-css icon-css-tb"></i></a>
                        <!--<i class="icon icon-submenu submenu2"></i>-->
                        <div>
                            <a href="">专业课</a>
                            <a href="">选修课</a>
                        </div>
                    </li>
                    <li data-index="2">
                        <a href="/admin/choice/index" class="first">选课列表<i class="icon-css icon-css-tb"></i></a>
                        <!--<i class="icon icon-submenu submenu2"></i>-->
                        <div>
                            <a href="">专业课</a>
                            <a href="">选修课</a>
                        </div>
                    </li>
                </ol>
                <!--                <a href="--><!--" class="icon icon-notice-bell">-->

            </div>
        </div>
    </div>
<div class="container">
    <div class="wrapper">
        <!-- 小面包屑导航 -->
        <!-- 小面包屑导航 -->
        <!-- 主内容 -->
        <div class="cloum mb0 notice">
            <!--				-->                <!-- 搜索框 -->
            <form method="post" class="search-box2 clearfix" id="J-search" action="/admin/choice/index">
                <!--					-->
                <!--					-->					<label for="reportPerson">学生姓名：</label>
                <input style="width:200px;" name="reportPerson" id="reportPerson" type="text">
                <input name="openTimeSearch" value="1" id="isTimeSearch" type="hidden">
                <input type="submit"name="submit" class="btn btn-default btn-middle  verti-middle-btn"  value="搜索" >  <br>
                <br>
                <span style="margin-left: 570px"></span>
            </form>
            <!--				-->                <!-- 通知列表 -->
            <div class="notice-list" id="J-notice-list">
                <table class="table">
                    <thead>
                    <tr>
                        <th class="dealPerson">学生编号</th>
                        <th class="reportTime">学生姓名</th>
                        <th class="orderId">课程编号</th>
                        <th class="orderTitle" style="width: 24%">课程名</th>
                    </tr>
                    </thead>
                    <tbody>
                    <!--合并页面-->
                    <?php foreach ($choice as $arr) {?>
                    <tr data-link="">
                        <td class="id"><?php echo $arr['id']; ?></td>
                        <td class="reportTime"><?php echo $arr['stuName']; ?></td>
                        <td class="read">
                            <?php echo $arr['courseNo']; ?>							</td>
                        <td class="orderId"><?php echo $arr['courseName']; ?></td>
                    </tr>
                    <?php }
?>
                    </tbody>
                    <tfoot>
                    <tr class="noborder form-inline">
                        <td colspan="11" class="left first">
                        </td>
                    </tr>
                    </tfoot>
                </table>
                <div class="pagination ovh">
                    <div class="ovh">
                        <?php echo $page; ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php $this->partial('common/footer');?>