<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>联系我们</title>
    <link rel="stylesheet" href="/admin/css/style.css" type="text/css" media="all">
</head>
<body>
<div id="append"></div>
<div class="container">
    <h3>修改学生</h3>
    <div class="mainbox">
        <form action="/admin/student/update" method="post">
            <table style="width:700px;">
                <td class="login">
                    <?php foreach ($student as $arr) {?>
                    <table class="login_tab">
                        <tr>
                            <td>学生姓名:</td>
                            <td><input type="text" id="name" tabindex="1" class="txt" name="name" value=<?php echo $arr['name']; ?> /></td>
                        </tr>
                        <tr>
                            <td><input type="hidden" id="name" tabindex="1" class="txt" name="id" value=<?php echo $arr['id']; ?> /></td>
                        </tr>
                        <tr>
                            <td>学生性别:</td>
                            <td><input type="text"  id="mobile" tabindex="2" class="txt" name="sex" value=<?php echo $arr['sex']; ?> /></td>
                        </tr>
                        <tr>
                            <td>qq:</td>
                            <td><input type="text"  id="phone" tabindex="2" class="txt" name="qq" value=  <?php echo $arr['qq']; ?>	 /></td>
                        </tr>
                        <tr>
                            <td>电话:</td>
                            <td><input type="text"  id="fax" tabindex="2" class="txt" name="phone" value=<?php echo $arr['phone']; ?> /></td>
                        </tr>

                    </table>
                    <?php }
?>
                </td>
                <tbody>
                <tr>
                    <td><input value="提 交" class="btn" type="submit"></td>
                </tr>

                </tbody>
            </table>
        </form>
    </div>
</div>
</body>
</html>
