<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>联系我们</title>
    <link rel="stylesheet" href="/admin/css/style.css" type="text/css" media="all">
</head>
<body>
<div id="append"></div>
<div class="container">
    <h3>添加课程</h3>
    <div class="mainbox">
        <form action="/admin/course/add" method="post">
            <table style="width:700px;">
                <td class="login">
                    <table class="login_tab">
                        <tr>
                            <td>课程名字:</td>
                            <td><input type="text" id="name" tabindex="1" class="txt" name="name"/></td>
                        </tr>
                    </table>
                </td>
                <tbody>
                <tr>
                    <td><input value="提 交" class="btn" type="submit"></td>
                </tr>

                </tbody>
            </table>
        </form>
    </div>
</div>
</body>
</html>
