<?php $this->partial('common/top');?>
    <div class="header bb">
        <!-- 导航栏 -->
        <div class="menu" id="J-menu">
            <!-- 顶栏 -->
            <div class="wrapper clearfix top">
                <ul class="quit clearfix">
                    <li style="border-left:0px"><a href="/admin/course/add"  id="search" style="color:#29a2da">添加课程</a></li>
                    <li style="border-left:0px"><a style="color:#29a2da" href="">列表查询</a></li>
                </ul>
            </div>
            <div class="wrapper clearfix">
                <a href="/admin/student/index" class="logo fl">
                    <img src="/admin/images/logo-new.png" alt="logo">
                    <span style="color: #29a2da;font-weight: 900;">学生管理系统</span>
                </a>
                <ol class="clearfix fl" id="J-menu-item">
                    <li class="active" data-index="3">
                        <a href="/admin/student/index" class="first" >学生列表<i class="icon-css icon-css-tb"></i></a>
                        <!--<i class="icon icon-submenu submenu3"></i>-->
                        <div>
                            <a href="">信息院</a>
                            <a href="">化院</a>
                            <a href="">物电学院</a>
                            <a href="">外国语学院</a>
                            <a href="">文学院</a>
                            <a href="">体育学院</a>
                            <a href="">经济学院</a>
                        </div>
                    </li>
                    <li data-index="2">
                        <a href="/admin/course/index" class="first">课程列表<i class="icon-css icon-css-tb"></i></a>
                        <!--<i class="icon icon-submenu submenu2"></i>-->
                        <div>
                            <a href="http://help-t.yaochufa.com/ycfad2014/document/index">专业课</a>
                            <a href="http://help-t.yaochufa.com/ycfad2014/document/category">选修课</a>
                        </div>
                    </li>
                    <li data-index="2">
                        <a href="/admin/choice/index" class="first">选课列表<i class="icon-css icon-css-tb"></i></a>
                        <!--<i class="icon icon-submenu submenu2"></i>-->
                        <div>
                            <a href="http://help-t.yaochufa.com/ycfad2014/user/userinfo">专业课</a>
                            <a href="http://help-t.yaochufa.com/ycfad2014/ordermanger/myorder">选修课</a>
                        </div>
                    </li>

                </ol>
                <!--                <a href="--><!--" class="icon icon-notice-bell">-->

            </div>
        </div>
    </div>
<!-- 主体 -->
<div class="container">
    <div class="wrapper">
        <!-- 小面包屑导航 -->
        <!-- 小面包屑导航 -->
        <!-- 主内容 -->
        <div class="cloum mb0 notice">
            <!--				-->                <!-- 搜索框 -->
            <form method="get" class="search-box2 clearfix" id="J-search" action="/admin/course/index">
                <!--					-->
                <!--					-->					<label for="reportPerson">课程名或课程编号：</label>
                <input style="width:200px;" name="reportPerson" id="reportPerson" type="text">
                <label for="orderStatus">状态：</label>
                <select id="status" name="orderStatus" class="form-control">
                    <option selected="selected" value="-1">全部</option>
                    <option value="0">语文</option>
                    <option value="1">软件</option>
                    <option value="2">测试</option>
                </select>
                <input name="openTimeSearch" value="1" id="isTimeSearch" type="hidden">
                <input type="submit"name="submit" class="btn btn-default btn-middle  verti-middle-btn"  value="搜索" >  <br>
                <br>
                <span style="margin-left: 570px"></span>

            </form>
            <!--				-->                <!-- 通知列表 -->
            <div class="notice-list" id="J-notice-list">
                <form action="/admin/course/delect" method="post">
                <table class="table">
                    <thead>
                    <tr>
                        <th class="dealPerson">删除</th>
                        <th class="dealPerson">课程编号</th>
                        <th class="reportTime">课程名称</th>
                        <th class="dealType">添加时间</th>
                        <th class="operate">操作</th>
                    </tr>
                    </thead>
                    <tbody>
                    <!--合并页面-->
                    <?php foreach ($course as $arr) {?>
                    <tr data-link="">
                        <td width="80"><input name="arr[]" value="<?php echo $arr['courseNo']; ?>" class="checkbox" type="checkbox"></td>
                        <td class="id"><?php echo $arr['courseNo']; ?></td>
                        <td class="reportTime"><?php echo $arr['name']; ?></td>
                        <td class="dealType">
                            <?php echo date("Y-m-d", $arr['time']); ?>							</td>
                        <td class="operate"> <a href="/admin/course/update?id=<?php echo $arr['courseNo']; ?>">修改</a></td>
                    </tr>
                    <?php }
?>
                    <td ><input value="提 交" class="btn" type="submit"></td>
                    </tbody>
                    <tfoot>
                    <tr class="noborder form-inline">
                        <td colspan="11" class="left first">
                        </td>
                    </tr>
                    </tfoot>
                </table>
                    </form>
                <div class="pagination ovh">
                    <div class="ovh">
                        <?php echo $page; ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<?php $this->partial('common/footer');?>